INSERT INTO CONTATOS(NOME) VALUES('marcelo');
INSERT INTO CONTATOS(NOME) VALUES('daniel');
INSERT INTO CONTATOS(NOME) VALUES('lucas');
INSERT INTO CONTATOS(NOME) VALUES('rodrigo');

INSERT INTO TELEFONES(NUMERO, TIPO, CONTATO_DONO_ID) VALUES(142, 'PESSOAL', 1);
INSERT INTO TELEFONES(NUMERO, TIPO, CONTATO_DONO_ID) VALUES(422, 'PESSOAL', 1);
INSERT INTO TELEFONES(NUMERO, TIPO, CONTATO_DONO_ID) VALUES(1512, 'PESSOAL', 1);
INSERT INTO TELEFONES(NUMERO, TIPO, CONTATO_DONO_ID) VALUES(14213, 'PESSOAL', 2);
INSERT INTO TELEFONES(NUMERO, TIPO, CONTATO_DONO_ID) VALUES(142123, 'PESSOAL', 3);
INSERT INTO TELEFONES(NUMERO, TIPO, CONTATO_DONO_ID) VALUES(1213, 'PESSOAL', 4);
INSERT INTO TELEFONES(NUMERO, TIPO, CONTATO_DONO_ID) VALUES(11232, 'PESSOAL', 4);

INSERT INTO EMAILS(EMAIL, TIPO, CONTATO_DONO_ID) VALUES('fsdf', 'PESSOAL', 1);
INSERT INTO EMAILS(EMAIL, TIPO, CONTATO_DONO_ID) VALUES('sad', 'PESSOAL', 1);
INSERT INTO EMAILS(EMAIL, TIPO, CONTATO_DONO_ID) VALUES('asdfa', 'PESSOAL', 2);
INSERT INTO EMAILS(EMAIL, TIPO, CONTATO_DONO_ID) VALUES('asda', 'PESSOAL', 2);
INSERT INTO EMAILS(EMAIL, TIPO, CONTATO_DONO_ID) VALUES('asgaa', 'PESSOAL', 3);
INSERT INTO EMAILS(EMAIL, TIPO, CONTATO_DONO_ID) VALUES('asdad', 'PESSOAL', 4);
INSERT INTO EMAILS(EMAIL, TIPO, CONTATO_DONO_ID) VALUES('asdas', 'PESSOAL', 4);



